---
title: "lab1"
author: "Holly Finertie"
date: "1/22/2020"
output: html_document
---

Installed packages previously
```{r}
library(maps)
```

Clear visualization parameter
```{r}
oldpar = par()
```

World map exists in maps package. Low resolution = less accurate boundaries
```{r, world}
## pull world map
world = map("world", res=0)

##shows structure
str(world)

##shows structure and names of componenets
head(world$names)

##displays points are layed out and would create polygon shape file - not an actual spatial object-
plot(world)
```

```{r, states}
states = map("state", res = 0)
str(states)
head(states$names)
plot(states)
```

```{r}
library(maptools)

## create lat/longitude projection (move from points to spatial object with coordinates)
spworld = map2SpatialLines(world, proj4string = CRS("+proj=longlat"))
spstates = map2SpatialLines(states, proj4string = CRS("+proj=longlat"))

## shows structure
str(spworld, max.level = 2)
str(spstates,max.level = 2)

## plot new spatial structures
plot(spworld)
plot(spstates)

```

```{r}
## transform coordinate reference system 
library(rgdal)

## applies coordinate reference system to specific lat/long for the center or EPSG number
world.laea <- spTransform(spworld, CRS("+proj=laea +lat_0=0 +lon_0=0"))
states.laea <- spTransform(spstates, CRS("+proj=laea +lat_0=43.0758 +lon_0=-89.3976"))
states.epsg <- spTransform(spstates, CRS("+init=epsg:3623"))
```

```{r}
#Displays transformed spatial objects as plots
par(mfrow = c(2, 2), pty = "s", cex.axis = 0.5)

plot(spworld, axes = T)
title(main = "Longitude and\nLatitude")
plot(world.laea, axes = T)
title(main = "Lambert Azimuthal\nEqual Area")
plot(spstates, axes = T)
title(main = "Longitude and\nLatitude")
plot(states.laea, axes = T)
title(main = "Lambert Azimuthal\nEqual Area")

```


#SPATIAL REFERENCING

```{r}
par(oldpar)

## restarting - repulled state file with points
map.states = map("state", plot = T, fill = T, res = 0)

str(map.states)
```


```{r}
# names are not exactly what we want
map.states$names

# split names by :
list.names.states = strsplit(map.states$names,":")

head(list.names.states)

# pulling first name in list of state names we just created
map.IDs = sapply(list.names.states, function(x) x[1])

# shows that this worked
head(map.IDs)

#creates spatial polygon, projected to lat/long
polystates = map2SpatialPolygons(map.states, IDs = map.IDs, proj4string = CRS("+proj=longlat"))

summary(polystates)

plot(polystates)
```


```{r}
## projecting with coordinate reference
states.laea = spTransform(polystates, CRS("+proj=laea +lat_0=43.0758 +lon_0=-89.3976"))
plot(states.laea)

#assigned map ids as the ids for the polygon
sp.IDs = sapply(slot(states.laea, "polygons"), function(x) slot(x,"ID"))
head(sp.IDs, n=50)


```

```{r}
## pull in SAT information
sat_verbal = read.csv("sat_verbal.csv", stringsAsFactors = F,row.names = 1)
head(sat_verbal, n=50)

## merge polygon and SAT data
states.verbal = SpatialPolygonsDataFrame(polystates,sat_verbal)
summary(states.verbal)

```

```{r}
## projected coordinates, doing the same thing
states.verbal.laea = spTransform(states.verbal, CRS("+proj=laea +lat_0=43.0758 +lon_0=-89.3976"))

plot(states.verbal.laea)
summary(states.verbal.laea)
```


```{r}
## loads package to bring in colors
library(RColorBrewer)

display.brewer.all()
display.brewer.pal(5, "Greens")

##
library(classInt)

## assign number of classes
plotvar = states.verbal.laea$verbal
nclr = 5

## assign colors
plotclr = brewer.pal(nclr, "Greens")
plotclr

##assign quantile classes 
class = classIntervals(plotvar, nclr, style = "quantile")
class

## round digits
colcode = findColours(class, plotclr, digits = 3)
colcode

## plot data!
plot(states.verbal.laea, col = colcode)

##re-doing with diff colors and adding legends/title
plotclr = brewer.pal(nclr, "Greens")
class = classIntervals(plotvar, nclr, style = "quantile")
colcode = findColours(class, plotclr, digits = 3)
plot(states.verbal.laea, col = colcode, border = "grey",axes = F)
title(main = "SAT verbal scores in 2010 \n by Holly Finertie", 
      sub = "Data Source: College Board")
legend("bottomleft", legend = names(attr(colcode,"table")), 
       fill = attr(colcode, "palette"), cex = 0.55)
```




